title: Kyle's awesome thinkings
name: Kyle
description: >- 
  UI/UX developer.
  Data and User Experiences are the most important things.
email: kyle.kim0305@gmail.com
github: ambrosiak

baseurl: ""
url: "http://ambrosiak.github.io"

markdown: kramdown

image: '/assets/images/default_blog_cover.png'
asset_url: /assets

google_analytics:
    ua: 'UA-91843902-3'