title: AMBROSIAK
name: KIM, KWANGMIN
description: |
  UI/UX developer.
  UX and Data maketh developer.
email: kyle.kim0305@gmail.com
github: ambrosiak
facebook: www.facebook.com/amazingloving

baseurl: ""
url: "http://ambrosiak.github.io"

markdown: kramdown

image: '/assets/images/default_blog_cover.jpeg'
asset_url: /assets

google_analytics:
    ua: 'UA-91843902-3'